<a href="https://colab.research.google.com/github/prabhsimran77/EXPLORATORY-DATA-ANALYSIS/blob/main/EDAsales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/store_sales.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Gender              5000 non-null   object
 3   Category            5000 non-null   object
 4   ItemPurchased       5000 non-null   object
 5   Amount              5000 non-null   float64
 6   Season              5000 non-null   object
 7   PaymentMethod       5000 non-null   object
 8   ItemRating          5000 non-null   float64
 9   DiscountApplied(%)  5000 non-null   int64
 10  PreviousPurchases   5000 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 429.8+ KB

In [ ]:
df.head()

,CustomerID,Age,Gender,Category,ItemPurchased,Amount,Season,PaymentMethod,ItemRating,DiscountApplied(%),PreviousPurchases
0,1,58,Female,Accessories,Handbag,115.50,Autumn,Card,3.5,18,4
1,2,40,Male,Mens Clothing,Shirt,103.43,Spring,Card,4.1,13,4
2,3,66,Female,Sports,Football,35.45,Spring,Card,3.3,11,3
3,4,39,Female,Accessories,Handbag,153.31,Spring,Card,4.4,13,4
4,5,23,Female,Home,Curtains,151.43,Winter,Card,4.1,20,10

In [ ]:
df.sample(n=10)

,CustomerID,Age,Gender,Category,ItemPurchased,Amount,Season,PaymentMethod,ItemRating,DiscountApplied(%),PreviousPurchases
775,776,52,Male,Footwear,Sandals,161.58,Spring,Card,2.6,22,11
3249,3250,58,Male,Sports,Dumbbells,246.31,Winter,Card,3.9,20,5
2732,2733,26,Female,Womens Clothing,Skirt,66.62,Autumn,Cash on Delivery,3.5,2,1
1575,1576,45,Female,Accessories,Sunglasses,159.73,Spring,Card,3.7,10,5
2172,2173,29,Female,Accessories,Wallet,65.65,Summer,Cash on Delivery,3.6,11,3
3464,3465,45,Female,Footwear,Sneakers,66.04,Spring,Card,3.7,11,3
2218,2219,57,Male,Electronics,Mobile Phone,1857.16,Autumn,Card,4.0,13,4
485,486,48,Female,Womens Clothing,Top,98.38,Winter,Cash on Delivery,4.2,14,2
68,69,35,Female,Beauty,Makeup Set,112.83,Spring,Card,3.8,10,5
411,412,69,Male,Sports,Dumbbells,31.84,Autumn,Cash on Delivery,4.0,18,4

In [ ]:
df.nunique()

CustomerID            5000
Age                     51
Gender                   2
Category                 9
ItemPurchased           30
Amount                4565
Season                   4
PaymentMethod            2
ItemRating              39
DiscountApplied(%)      32
PreviousPurchases       14
dtype: int64

In [ ]:
  sns.countplot(x='Gender', data=df)

In [ ]:
df['Gender'].value_counts(normalize=True).plot(
    kind='pie',
    autopct='%.1f%%'
)

In [ ]:
sns.histplot(x='Age',data=df)

In [ ]:
sns.histplot(x='Gender',hue='Category',data=df)

In [ ]:
sns.countplot(y='ItemPurchased',data=df)

In [ ]:
order = df['ItemPurchased'].value_counts().index

sns.countplot(y='ItemPurchased', data=df, order=order)

In [ ]:
sns.countplot(x='PaymentMethod',data=df)

In [ ]:
df['Category'].unique()

In [ ]:
sns.set_style("whitegrid")
sns.countplot(y='Category',data=df)

In [ ]:
table = pd.crosstab(df['Gender'], df['Category'])
sns.heatmap(table, annot=True, fmt='d', cmap='Blues')

In [ ]:
plt.figure(figsize=(12, 12))
table = pd.crosstab(df['Gender'], df['ItemPurchased'])
sns.heatmap(table, annot=False,cmap='Blues')

In [ ]:
plt.figure(figsize=(12, 6))
male_df = df[df['Gender'] == 'Male']
table_male = pd.crosstab(male_df['Gender'], male_df['ItemPurchased'])
sns.heatmap(table_male, annot=True, fmt='d', cmap='Blues')

In [ ]:
plt.figure(figsize=(12, 6))
female_df = df[df['Gender'] == 'Female']
table_female = pd.crosstab(female_df['Gender'], female_df['ItemPurchased'])
sns.heatmap(table_female, annot=True, fmt='d', cmap='Blues')

In [ ]:
df['ItemPurchased'].nunique()

In [ ]:
sns.countplot(x='PaymentMethod',hue='Gender',data=df)

In [ ]:
sns.countplot(x='Gender',hue='PaymentMethod',data=df)

In [ ]:
ct=pd.crosstab(
    df['Gender'],
    df['PaymentMethod'],
    normalize='index'
) * 100
print(ct)

In [ ]:
sns.barplot(x='ItemRating',y='ItemPurchased',data=df)#no insights

In [ ]:
sns.scatterplot(x='ItemRating', y='ItemPurchased', data=df)#no insights

In [ ]:
plt.figure(figsize=(18, 8))#similar done with heatmap above
sns.countplot(x='Gender',hue='ItemPurchased',data=df)
plt.show()

In [ ]:
plt.figure(figsize=(18, 8))
sns.countplot(x='Category',hue='Season',data=df)

In [ ]:
sns.boxplot(x='DiscountApplied(%)',y='PaymentMethod',data=df)

In [ ]:
sns.scatterplot(x='Age',y='DiscountApplied(%)',hue='PreviousPurchases',data=df)#no insights

In [ ]:
sns.scatterplot(x='Amount',y='DiscountApplied(%)',hue='PreviousPurchases',data=df)#no insights

In [ ]:
ct = pd.crosstab([df['ItemPurchased'], df['Category']], male_df['Gender'])
sns.heatmap(ct, annot=True, fmt='d',cmap='Blues')
plt.figure(figsize=(10, 12))

In [ ]:
ct = pd.crosstab([df['ItemPurchased'], df['Category']], female_df['Gender'])
sns.heatmap(ct, annot=True, fmt='d',cmap='Blues')
plt.figure(figsize=(10, 12))

In [ ]:
sns.scatterplot(x='PreviousPurchases',y='DiscountApplied(%)',data=df)

In [ ]:
sns.scatterplot(x='PreviousPurchases',y='DiscountApplied(%)',hue='Amount',data=df)#no insights

In [ ]:
!pip install ydata-profiling
from ydata_profiling import ProfileReport

In [ ]:
df = pd.read_csv("/content/store_sales.csv")

# Generate the profile report
profile = ProfileReport(df, title="store_sales")

# Display the report in a Jupyter Notebook
profile.to_notebook_iframe()

# Save the report to an HTML file
profile.to_file("store_sales.html")